all:
	javac Hello.java -classpath "../.."
	javac Frequencer.java -classpath "../.."
	javac InformationEstimator.java -classpath "../.."
	javac TestCase.java -classpath "../.."
	
win:
	javac -encoding UTF-8 Hello.java -classpath "../.."
	javac -encoding UTF-8  Frequencer.java -classpath "../.."
	javac -encoding UTF-8  InformationEstimator.java -classpath "../.."
	javac -encoding UTF-8  TestCase.java -classpath "../.."
	
run:
#	java -classpath "../.." s4.B193317/Hello
#	java -classpath "../.." s4.B193317/Frequencer
#	java -classpath "../.." s4.B193317/InformationEstimator
	java -classpath "../.." s4.B193317/TestCase
